name: gomokupro
description: God Tier AI Gomoku
publish_to: 'none'
version: 5.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
