name: ios18_gomoku
description: Native iOS 18 Stockfish Gomoku
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6 # Icon chuáº©n Apple

flutter:
  uses-material-design: true
